name: Mirror Docker images

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  mirror:
    name: Mirror
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: imjasonh/setup-crane@v0.3
      - name: Mirror
        run: |
          ./mirror.sh
